name: Java Build and Test

on: 
  repository_dispatch:
    types: [code_submission]

jobs:
  build:
    runs-on: ubuntu-latest  # You can use windows-latest or macos-latest if needed

    steps:
    - uses: actions/checkout@v2  # Checks out the code in the repository

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'  # Sets up JDK 11

    - name: Compile Java code
      run: javac ${{ secrets.JAVA_FILE }}  # Compiles the Java file

    - name: Run Java Program
      run: java ${{ secrets.JAVA_CLASS }}  # Runs the compiled Java program

    - name: Run Tests
      run: |
        # Command to run tests if applicable
        java -cp . ${{ secrets.JAVA_TEST_CLASS }}  # Example for running tests
